pratique_ar/config/routes.rb
Rails.application.routes.draw do
  resources :employee_educations
  root to: "home#page"
  resources :cities
  resources :countries
  resources :customers, except: [:destroy]
  resources :suppliers, except: [:destroy]
  resources :shippers
  resources :products
  resources :order_details
  resources :employees
  resources :categories, except: [:destroy]
  resources :orders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

pratique_ar/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pratique_ar/app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

pratique_ar/app/models/city.rb
class City < ApplicationRecord
  belongs_to :country, optional: false
end

pratique_ar/app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
end

pratique_ar/app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :country, optional: false
	belongs_to :city #TODO: add optional: false
end

pratique_ar/app/models/employee.rb
class Employee < ApplicationRecord
end

pratique_ar/app/models/employee_education.rb
class EmployeeEducation < ApplicationRecord
  belongs_to :employee
end

pratique_ar/app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	belongs_to :employee
	belongs_to :shipper
	has_many :order_details
end

pratique_ar/app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :product
end

pratique_ar/app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :supplier
end

pratique_ar/app/models/shipper.rb
class Shipper < ApplicationRecord
	has_many :orders
end

pratique_ar/app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :products
	belongs_to :country, optional: false
	belongs_to :city #TODO: add optional: false
end

pratique_ar/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: %i[ show edit update destroy ]

  # GET /cities or /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1 or /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to city_url(@city), notice: "City was successfully created." }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to city_url(@city), notice: "City was successfully updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url, notice: "City was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:name, :country_id)
    end
end

pratique_ar/app/helpers/categories_helper.rb
module CategoriesHelper
end

pratique_ar/app/helpers/cities_helper.rb
module CitiesHelper
end

pratique_ar/app/helpers/countries_helper.rb
module CountriesHelper
end

pratique_ar/app/helpers/customers_helper.rb
module CustomersHelper
end

pratique_ar/app/helpers/employees_helper.rb
module EmployeesHelper
end

pratique_ar/app/helpers/home_helper.rb
module HomeHelper
end

pratique_ar/app/helpers/orders_helper.rb
module OrdersHelper
end

pratique_ar/app/helpers/products_helper.rb
module ProductsHelper
end

pratique_ar/app/helpers/shippers_helper.rb
module ShippersHelper
end

pratique_ar/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

pratique_ar/app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country_id %>
    <%= form.text_field :country_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

pratique_ar/app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

pratique_ar/app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th style="width:30%" colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= link_to city.country.name, country_path(city.country) %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

pratique_ar/app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

pratique_ar/app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @city.country.name %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>