pratique_ar/config/routes.rb
Rails.application.routes.draw do
  resources :employee_educations
  root to: "home#page"
  resources :cities
  resources :countries
  resources :customers, except: [:destroy]
  resources :suppliers, except: [:destroy]
  resources :shippers
  resources :products
  resources :order_details
  resources :employees
  resources :categories, except: [:destroy]
  resources :orders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

pratique_ar/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pratique_ar/app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

pratique_ar/app/models/city.rb
class City < ApplicationRecord
  belongs_to :country, optional: false
end

pratique_ar/app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
end

pratique_ar/app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :country, optional: false
	belongs_to :city #TODO: add optional: false
end

pratique_ar/app/models/employee.rb
class Employee < ApplicationRecord
end

pratique_ar/app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	belongs_to :employee
	belongs_to :shipper
	has_many :order_details
end

pratique_ar/app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :product
end

pratique_ar/app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :supplier
end

pratique_ar/app/models/shipper.rb
class Shipper < ApplicationRecord
	has_many :orders
end

pratique_ar/app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :products
	belongs_to :country, optional: false
	belongs_to :city #TODO: add optional: false
end

pratique_ar/app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
  before_action :set_order_detail, only: %i[ show edit update destroy ]

  # GET /order_details or /order_details.json
  def index
    @order_details = restricted_index(OrderDetail)
  end

  # GET /order_details/1 or /order_details/1.json
  def show
  end

  # GET /order_details/new
  def new
    @order_detail = OrderDetail.new
  end

  # GET /order_details/1/edit
  def edit
  end

  # POST /order_details or /order_details.json
  def create
    @order_detail = OrderDetail.new(order_detail_params)

    respond_to do |format|
      if @order_detail.save
        format.html { redirect_to order_detail_url(@order_detail), notice: "Order detail was successfully created." }
        format.json { render :show, status: :created, location: @order_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_details/1 or /order_details/1.json
  def update
    respond_to do |format|
      if @order_detail.update(order_detail_params)
        format.html { redirect_to order_detail_url(@order_detail), notice: "Order detail was successfully updated." }
        format.json { render :show, status: :ok, location: @order_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_details/1 or /order_details/1.json
  def destroy
    @order_detail.destroy

    respond_to do |format|
      format.html { redirect_to order_details_url, notice: "Order detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_detail
      @order_detail = OrderDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_detail_params
      params.require(:order_detail).permit(:order_id, :product_id, :quantity)
    end
end

pratique_ar/app/helpers/categories_helper.rb
module CategoriesHelper
end

pratique_ar/app/helpers/cities_helper.rb
module CitiesHelper
end

pratique_ar/app/helpers/countries_helper.rb
module CountriesHelper
end

pratique_ar/app/helpers/customers_helper.rb
module CustomersHelper
end

pratique_ar/app/helpers/employees_helper.rb
module EmployeesHelper
end

pratique_ar/app/helpers/home_helper.rb
module HomeHelper
end

pratique_ar/app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

pratique_ar/app/helpers/orders_helper.rb
module OrdersHelper
end

pratique_ar/app/helpers/products_helper.rb
module ProductsHelper
end

pratique_ar/app/helpers/shippers_helper.rb
module ShippersHelper
end

pratique_ar/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

pratique_ar/app/views/order_details/_form.html.erb
<%= form_with(model: order_detail, local: true) do |form| %>
  <% if order_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_detail.errors.count, "error") %> prohibited this order_detail from being saved:</h2>

      <ul>
        <% order_detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.number_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

pratique_ar/app/views/order_details/edit.html.erb
<h1>Editing Order Detail</h1>

<%= render 'form', order_detail: @order_detail %>

<%= link_to 'Show', @order_detail %> |
<%= link_to 'Back', order_details_path %>

pratique_ar/app/views/order_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Details</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Product</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_details.each do |order_detail| %>
      <tr>
        <td><%= link_to "#{order_detail.order_id}", order_path(order_detail.order_id) %></td>
        <td><%= link_to "#{order_detail.product.product_name}", product_path(order_detail.product_id) %></td>
        <td><%= order_detail.quantity %></td>
        <td><%= link_to 'Show', order_detail %></td>
        <td><%= link_to 'Edit', edit_order_detail_path(order_detail) %></td>
        <td><%= link_to 'Destroy', order_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Detail', new_order_detail_path %>

pratique_ar/app/views/order_details/new.html.erb
<h1>New Order Detail</h1>

<%= render 'form', order_detail: @order_detail %>

<%= link_to 'Back', order_details_path %>

pratique_ar/app/views/order_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order_detail.order_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order_detail.product.product_name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_detail.quantity %>
</p>

<%= link_to 'Edit', edit_order_detail_path(@order_detail) %> |
<%= link_to 'Back', order_details_path %>