pratique_ar/config/routes.rb
Rails.application.routes.draw do
  resources :employee_educations
  root to: "home#page"
  resources :cities
  resources :countries
  resources :customers, except: [:destroy]
  resources :suppliers, except: [:destroy]
  resources :shippers
  resources :products
  resources :order_details
  resources :employees
  resources :categories, except: [:destroy]
  resources :orders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

pratique_ar/app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

pratique_ar/app/models/city.rb
class City < ApplicationRecord
  belongs_to :country, optional: false
end

pratique_ar/app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
end

pratique_ar/app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :country, optional: false
	belongs_to :city #TODO: add optional: false
end

pratique_ar/app/models/employee.rb
class Employee < ApplicationRecord
end

pratique_ar/app/models/employee_education.rb
class EmployeeEducation < ApplicationRecord
  belongs_to :employee
end

pratique_ar/app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	belongs_to :employee
	belongs_to :shipper
	has_many :order_details
end

pratique_ar/app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :product
end

pratique_ar/app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :supplier
end

pratique_ar/app/models/shipper.rb
class Shipper < ApplicationRecord
	has_many :orders
end

pratique_ar/app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :products
	belongs_to :country, optional: false
	belongs_to :city #TODO: add optional: false
end

pratique_ar/app/controllers/employee_educations_controller.rb
class EmployeeEducationsController < ApplicationController
  before_action :set_employee_education, only: %i[ show edit update destroy ]

  # GET /employee_educations or /employee_educations.json
  def index
    @employee_educations = EmployeeEducation.all
  end

  # GET /employee_educations/1 or /employee_educations/1.json
  def show
  end

  # GET /employee_educations/new
  def new
    @employee_education = EmployeeEducation.new
  end

  # GET /employee_educations/1/edit
  def edit
  end

  # POST /employee_educations or /employee_educations.json
  def create
    @employee_education = EmployeeEducation.new(employee_education_params)

    respond_to do |format|
      if @employee_education.save
        format.html { redirect_to employee_education_url(@employee_education), notice: "Employee education was successfully created." }
        format.json { render :show, status: :created, location: @employee_education }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee_education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_educations/1 or /employee_educations/1.json
  def update
    respond_to do |format|
      if @employee_education.update(employee_education_params)
        format.html { redirect_to employee_education_url(@employee_education), notice: "Employee education was successfully updated." }
        format.json { render :show, status: :ok, location: @employee_education }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee_education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_educations/1 or /employee_educations/1.json
  def destroy
    @employee_education.destroy

    respond_to do |format|
      format.html { redirect_to employee_educations_url, notice: "Employee education was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_education
      @employee_education = EmployeeEducation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_education_params
      params.require(:employee_education).permit(:institution, :degree, :date_obtained, :completed, :employee_id)
    end
end

pratique_ar/app/helpers/categories_helper.rb
module CategoriesHelper
end

pratique_ar/app/helpers/cities_helper.rb
module CitiesHelper
end

pratique_ar/app/helpers/countries_helper.rb
module CountriesHelper
end

pratique_ar/app/helpers/customers_helper.rb
module CustomersHelper
end

pratique_ar/app/helpers/employee_educations_helper.rb
module EmployeeEducationsHelper
end

pratique_ar/app/helpers/employees_helper.rb
module EmployeesHelper
end

pratique_ar/app/helpers/home_helper.rb
module HomeHelper
end

pratique_ar/app/helpers/orders_helper.rb
module OrdersHelper
end

pratique_ar/app/helpers/products_helper.rb
module ProductsHelper
end

pratique_ar/app/helpers/shippers_helper.rb
module ShippersHelper
end

pratique_ar/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

pratique_ar/app/views/employee_educations/_form.html.erb
<%= form_with(model: employee_education, local: true) do |form| %>
  <% if employee_education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee_education.errors.count, "error") %> prohibited this employee_education from being saved:</h2>

      <ul>
        <% employee_education.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :institution %>
    <%= form.text_field :institution %>
  </div>

  <div class="field">
    <%= form.label :degree %>
    <%= form.text_field :degree %>
  </div>

  <div class="field">
    <%= form.label :date_obtained %>
    <%= form.date_select :date_obtained %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.text_field :employee_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

pratique_ar/app/views/employee_educations/edit.html.erb
<h1>Editing Employee Education</h1>

<%= render 'form', employee_education: @employee_education %>

<%= link_to 'Show', @employee_education %> |
<%= link_to 'Back', employee_educations_path %>

pratique_ar/app/views/employee_educations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee Educations</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Institution</th>
      <th>Degree</th>
      <th>Date obtained</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_educations.each do |employee_education| %>
      <tr>
        <td><%= link_to "#{employee_education.employee.first_name} #{employee_education.employee.last_name}", employee_path(employee_education.employee.id) %></td>
        <td><%= employee_education.institution %></td>
        <td><%= employee_education.degree %></td>
        <td><%= employee_education.date_obtained %></td>
        <td><%= employee_education.completed %></td>
        <td><%= link_to 'Show', employee_education %></td>
        <td><%= link_to 'Edit', edit_employee_education_path(employee_education) %></td>
        <td><%= link_to 'Destroy', employee_education, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee Education', new_employee_education_path %>

pratique_ar/app/views/employee_educations/new.html.erb
<h1>New Employee Education</h1>

<%= render 'form', employee_education: @employee_education %>

<%= link_to 'Back', employee_educations_path %>

pratique_ar/app/views/employee_educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Institution:</strong>
  <%= @employee_education.institution %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @employee_education.degree %>
</p>

<p>
  <strong>Date obtained:</strong>
  <%= @employee_education.date_obtained %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @employee_education.completed %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @employee_education.employee_id %>
</p>

<%= link_to 'Edit', edit_employee_education_path(@employee_education) %> |
<%= link_to 'Back', employee_educations_path %>