pratique_ar/config/routes.rb
Rails.application.routes.draw do
  resources :employee_educations
  root to: "home#page"
  resources :cities
  resources :countries
  resources :customers, except: [:destroy]
  resources :suppliers, except: [:destroy]
  resources :shippers
  resources :products
  resources :order_details
  resources :employees
  resources :categories, except: [:destroy]
  resources :orders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

pratique_ar/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pratique_ar/app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

pratique_ar/app/models/city.rb
class City < ApplicationRecord
  belongs_to :country, optional: false
end

pratique_ar/app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
end

pratique_ar/app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :country, optional: false
	belongs_to :city #TODO: add optional: false
end

pratique_ar/app/models/employee.rb
class Employee < ApplicationRecord
end

pratique_ar/app/models/employee_education.rb
class EmployeeEducation < ApplicationRecord
  belongs_to :employee
end

pratique_ar/app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	belongs_to :employee
	belongs_to :shipper
	has_many :order_details
end

pratique_ar/app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :product
end

pratique_ar/app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :supplier
end

pratique_ar/app/models/shipper.rb
class Shipper < ApplicationRecord
	has_many :orders
end

pratique_ar/app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :products
	belongs_to :country, optional: false
	belongs_to :city #TODO: add optional: false
end

pratique_ar/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = restricted_index(Category)
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category_name, :description)
    end
end

pratique_ar/app/helpers/categories_helper.rb
module CategoriesHelper
end

pratique_ar/app/helpers/cities_helper.rb
module CitiesHelper
end

pratique_ar/app/helpers/countries_helper.rb
module CountriesHelper
end

pratique_ar/app/helpers/customers_helper.rb
module CustomersHelper
end

pratique_ar/app/helpers/employees_helper.rb
module EmployeesHelper
end

pratique_ar/app/helpers/home_helper.rb
module HomeHelper
end

pratique_ar/app/helpers/orders_helper.rb
module OrdersHelper
end

pratique_ar/app/helpers/products_helper.rb
module ProductsHelper
end

pratique_ar/app/helpers/shippers_helper.rb
module ShippersHelper
end

pratique_ar/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

pratique_ar/app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_name %>
    <%= form.text_field :category_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

pratique_ar/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

pratique_ar/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category_name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Products', products_path(field_name: :category_id, value:category.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

pratique_ar/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

pratique_ar/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category name:</strong>
  <%= @category.category_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>